### ISSUE TITLE
GitHub Actions failing due to spending limits

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-r#125]
Hey @kuriwaki first of all, thanks, as always, for maintaining the R package for Dataverse! ❤️ 

As you may have noticed, GitHub Action are failing: https://github.com/IQSS/dataverse-client-r/actions/runs/4028390959

The error seems clear enough:

"The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings."

I'll see what can be done about this. Please sit tight!

**Comment by kuriwaki** [comment]
Thank you! On my end I cannot see how much all the spending is costing. Depending on what you find, it's probably fine to stop running daily checks. cc @wibeasley

**Comment by wibeasley** [comment]
How frequently is the Dataverse server software changing?  Because that's what the daily checks are mostly about (ie, to make sure some change in the server software does something the R package doesn't expect).  I think we'd want to catch problems in the first 24 hours, instead waiting for a weekly check to fire.  Plus the daily run looks very minimal: just one R version on one OS: https://github.com/IQSS/dataverse-client-r/blob/master/.github/workflows/R-CMD-check-daily.yaml

The [thorough GitHub Action](https://github.com/IQSS/dataverse-client-r/blob/master/.github/workflows/R-CMD-check-thorough.yaml) evaluates five builds (R version crossed with OS).  But that's only triggered right before pulling to the main branch.

Some things have been updated with R's GitHub Actions.  Maybe the newer version are more efficient and use less resources on GitHub Actions? 

@pdurbin, do you know how frequently the other clients run checks?

**Comment by pdurbin** [comment]
@wibeasley at this point I don't even know how many hours Dataverse itself uses on GitHub Actions. 😄 I assume it uses the most, just based on activity (commits to PRs mostly).

Also, I wrote "spending limits" but it also could have been a failed payment according to the error message. Please stay tuned!

**Comment by pdurbin** [comment]
@kuriwaki @wibeasley I don't have any new information for you (sorry!) but it's a new month and GitHub Actions seem to be working again over at the main "dataverse" repo. Are the working here too?

**Comment by wibeasley** [comment]
@kuriwaki, if you don't have a push ready, remember you can click the "rerun jobs" button.

https://github.com/IQSS/dataverse-client-r/actions/runs/4028699848

**Comment by mreekie** [comment]
@pdurbin, @kuriwaki I've opened [Spike: Discover Root cause of GitHub actions stoppage in January (Before the end of February!) #9355)(https://github.com/IQSS/dataverse/issues/9355)

At our next prio meeting I'm going to see if we can get this into our next sprint.
If you think that the new issue is adequate to replace this issue, feel free to close this.

**Comment by pdurbin** [comment]
Yes, good idea to move the conversation there. Closing.
