### ISSUE TITLE
More verbose httr error message for get_file()

### ISSUE THREAD

**Issue by EdJeeOnGitHub** [IQSS/dataverse-client-r#31]
I often find `get_file()` errors since the API can't return a certain [file format](https://dataverse.harvard.edu/api/access/datafile/2972336?format=original). Since the dataverse API returns informative messages when a request fails it makes sense to pass this along in R instead of just the default from `httr::stop_for_status()`.

For instance:

```R
library(dataverse)
library(tidyverse)

IPA_dataset <- get_dataset("doi:10.7910/DVN/JGLOZF")
# doi:  https://doi.org/10.7910/DVN/JGLOZF
community_files <- IPA_dataset$files$id %>% 
  map(function(x){
    print(x)
    return(get_file(x))
  })

```

after the [PR](https://github.com/IQSS/dataverse-client-r/pull/30) will return:
>   Not Found (HTTP 404). Failed to '/api/v1/access/datafile/2972336' datafile access error: requested optional service (image scaling, format conversion, etc.) is not supported on this datafile.

instead of:

>  Error in get_file(x) : Not Found (HTTP 404).

**Comment by kuriwaki** [comment]
I like this feature very much. (See below for a reprex).

Your current IPA example fails to give the intended error (i.e. it actually passes without any error messages) because in #39 we bypassed query when the targetwas not a `.tab` file (4d45330).  That was a stopgap and should be revisited... in the meantime, are there any examples of `.tab` files for which we'd get an informative error message?  We can put that in a testthat too.

``` r
# Get `ReadMe with Codebook.docx` (https://doi.org/10.7910/DVN/JGLOZF/GYZ7OQ, id = 2972336)
# master branch
library(dataverse)
get_file(2972336, server = "demo.dataverse.org") # wrong server
#> Error in get_file(2972336, server = "demo.dataverse.org"): Not Found (HTTP 404).
```

``` r
# EdJeeOnGitHub fork branch
library(dataverse)
get_file(2972336, server = "demo.dataverse.org") # wrong server
#> Error in get_file(2972336, server = "demo.dataverse.org"): Not Found (HTTP 404). Failed to API endpoint does not exist on this server. Please check your code for typos, or consult our API guide at http://guides.dataverse.org..
```

<sup>Created on 2020-12-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by EdJeeOnGitHub** [comment]
Thanks!

Back in Nov 2019 it was definitely throwing errors but things seem to have changed quite a bit since then - I think the pull request was meant to be incorporated some time ago but seems to have fallen through the cracks. 

I haven't touched any dataverse data in a while now so don't have any handy candidates for test cases I'm afraid.
